#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Migracion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SAAPA")]
	public partial class SAAPADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertBrokersReferido(BrokersReferido instance);
    partial void UpdateBrokersReferido(BrokersReferido instance);
    partial void DeleteBrokersReferido(BrokersReferido instance);
    partial void InsertBrokersAltaEjecutivo(BrokersAltaEjecutivo instance);
    partial void UpdateBrokersAltaEjecutivo(BrokersAltaEjecutivo instance);
    partial void DeleteBrokersAltaEjecutivo(BrokersAltaEjecutivo instance);
    partial void InsertBrokersMigrar(BrokersMigrar instance);
    partial void UpdateBrokersMigrar(BrokersMigrar instance);
    partial void DeleteBrokersMigrar(BrokersMigrar instance);
    #endregion
		
		public SAAPADataContext() : 
				base(global::CRM_Migracion.Properties.Settings.Default.SAAPAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SAAPADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAAPADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAAPADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAAPADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BrokersReferido> BrokersReferido
		{
			get
			{
				return this.GetTable<BrokersReferido>();
			}
		}
		
		public System.Data.Linq.Table<BrokersAltaEjecutivo> BrokersAltaEjecutivo
		{
			get
			{
				return this.GetTable<BrokersAltaEjecutivo>();
			}
		}
		
		public System.Data.Linq.Table<BrokersMigrar> BrokersMigrar
		{
			get
			{
				return this.GetTable<BrokersMigrar>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="[.dbo].ActualizarReferido")]
		public int ActualizarReferido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReferido", DbType="Int")] System.Nullable<int> idReferido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferido);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="[.dbo].InsertarReferido")]
		public int InsertarReferido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReferido", DbType="Int")] System.Nullable<int> idReferido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferido);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="[.dbo].InsertarAlFinalBrokersReferido")]
		public int InsertarAlFinalBrokersReferido([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idReferido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferido);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="[.dbo].ActualizarTablasRelacinadasReferidos")]
		public int ActualizarTablasRelacinadasReferidos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReferidoN", DbType="Int")] System.Nullable<int> idReferidoN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReferidoV", DbType="Int")] System.Nullable<int> idReferidoV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferidoN, idReferidoV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="[.dbo].ActualizarAltaEjecutivo")]
		public int ActualizarAltaEjecutivo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReferido", DbType="Int")] System.Nullable<int> idReferido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferido);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="[.dbo].InsertarAlFinalAltaEjecutivo")]
		public int InsertarAlFinalAltaEjecutivo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idReferido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferido);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="[.dbo].InsertarAltaEjecutivo")]
		public int InsertarAltaEjecutivo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReferido", DbType="Int")] System.Nullable<int> idReferido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferido);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BrokersReferido")]
	public partial class BrokersReferido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdBroker;
		
		private string _Nombre;
		
		private System.Nullable<int> _IdTipoReferido;
		
		private System.Nullable<System.Guid> _UserIdRegistro;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private System.Nullable<bool> _Activo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdBrokerChanging(System.Nullable<int> value);
    partial void OnIdBrokerChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdTipoReferidoChanging(System.Nullable<int> value);
    partial void OnIdTipoReferidoChanged();
    partial void OnUserIdRegistroChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdRegistroChanged();
    partial void OnFechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRegistroChanged();
    partial void OnActivoChanging(System.Nullable<bool> value);
    partial void OnActivoChanged();
    #endregion
		
		public BrokersReferido()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBroker", DbType="Int")]
		public System.Nullable<int> IdBroker
		{
			get
			{
				return this._IdBroker;
			}
			set
			{
				if ((this._IdBroker != value))
				{
					this.OnIdBrokerChanging(value);
					this.SendPropertyChanging();
					this._IdBroker = value;
					this.SendPropertyChanged("IdBroker");
					this.OnIdBrokerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(200)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoReferido", DbType="Int")]
		public System.Nullable<int> IdTipoReferido
		{
			get
			{
				return this._IdTipoReferido;
			}
			set
			{
				if ((this._IdTipoReferido != value))
				{
					this.OnIdTipoReferidoChanging(value);
					this.SendPropertyChanging();
					this._IdTipoReferido = value;
					this.SendPropertyChanged("IdTipoReferido");
					this.OnIdTipoReferidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIdRegistro", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserIdRegistro
		{
			get
			{
				return this._UserIdRegistro;
			}
			set
			{
				if ((this._UserIdRegistro != value))
				{
					this.OnUserIdRegistroChanging(value);
					this.SendPropertyChanging();
					this._UserIdRegistro = value;
					this.SendPropertyChanged("UserIdRegistro");
					this.OnUserIdRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BrokersAltaEjecutivo")]
	public partial class BrokersAltaEjecutivo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdInmobiliaria;
		
		private string _Nombre;
		
		private string _SegundoNombre;
		
		private string _ApellidoPaterno;
		
		private string _ApellidoMaterno;
		
		private System.DateTime _FechaRegistro;
		
		private System.Nullable<System.Guid> _UserIdRegistro;
		
		private bool _activo;
		
		private string _Correo;
		
		private string _Telefono;
		
		private System.Nullable<int> _IdBrokerEmpleado;
		
		private string _Curp;
		
		private System.Nullable<System.DateTime> _FechaCumpleaños;
		
		private System.Nullable<System.Guid> _UserIdAsignado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdInmobiliariaChanging(int value);
    partial void OnIdInmobiliariaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnSegundoNombreChanging(string value);
    partial void OnSegundoNombreChanged();
    partial void OnApellidoPaternoChanging(string value);
    partial void OnApellidoPaternoChanged();
    partial void OnApellidoMaternoChanging(string value);
    partial void OnApellidoMaternoChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnUserIdRegistroChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdRegistroChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnIdBrokerEmpleadoChanging(System.Nullable<int> value);
    partial void OnIdBrokerEmpleadoChanged();
    partial void OnCurpChanging(string value);
    partial void OnCurpChanged();
    partial void OnFechaCumpleañosChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCumpleañosChanged();
    partial void OnUserIdAsignadoChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdAsignadoChanged();
    #endregion
		
		public BrokersAltaEjecutivo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInmobiliaria", DbType="Int NOT NULL")]
		public int IdInmobiliaria
		{
			get
			{
				return this._IdInmobiliaria;
			}
			set
			{
				if ((this._IdInmobiliaria != value))
				{
					this.OnIdInmobiliariaChanging(value);
					this.SendPropertyChanging();
					this._IdInmobiliaria = value;
					this.SendPropertyChanged("IdInmobiliaria");
					this.OnIdInmobiliariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="NVarChar(50)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this.OnSegundoNombreChanging(value);
					this.SendPropertyChanging();
					this._SegundoNombre = value;
					this.SendPropertyChanged("SegundoNombre");
					this.OnSegundoNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPaterno", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoPaterno
		{
			get
			{
				return this._ApellidoPaterno;
			}
			set
			{
				if ((this._ApellidoPaterno != value))
				{
					this.OnApellidoPaternoChanging(value);
					this.SendPropertyChanging();
					this._ApellidoPaterno = value;
					this.SendPropertyChanged("ApellidoPaterno");
					this.OnApellidoPaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMaterno", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoMaterno
		{
			get
			{
				return this._ApellidoMaterno;
			}
			set
			{
				if ((this._ApellidoMaterno != value))
				{
					this.OnApellidoMaternoChanging(value);
					this.SendPropertyChanging();
					this._ApellidoMaterno = value;
					this.SendPropertyChanged("ApellidoMaterno");
					this.OnApellidoMaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIdRegistro", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserIdRegistro
		{
			get
			{
				return this._UserIdRegistro;
			}
			set
			{
				if ((this._UserIdRegistro != value))
				{
					this.OnUserIdRegistroChanging(value);
					this.SendPropertyChanging();
					this._UserIdRegistro = value;
					this.SendPropertyChanged("UserIdRegistro");
					this.OnUserIdRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(70)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBrokerEmpleado", DbType="Int")]
		public System.Nullable<int> IdBrokerEmpleado
		{
			get
			{
				return this._IdBrokerEmpleado;
			}
			set
			{
				if ((this._IdBrokerEmpleado != value))
				{
					this.OnIdBrokerEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdBrokerEmpleado = value;
					this.SendPropertyChanged("IdBrokerEmpleado");
					this.OnIdBrokerEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curp", DbType="NVarChar(18)")]
		public string Curp
		{
			get
			{
				return this._Curp;
			}
			set
			{
				if ((this._Curp != value))
				{
					this.OnCurpChanging(value);
					this.SendPropertyChanging();
					this._Curp = value;
					this.SendPropertyChanged("Curp");
					this.OnCurpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCumpleaños", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCumpleaños
		{
			get
			{
				return this._FechaCumpleaños;
			}
			set
			{
				if ((this._FechaCumpleaños != value))
				{
					this.OnFechaCumpleañosChanging(value);
					this.SendPropertyChanging();
					this._FechaCumpleaños = value;
					this.SendPropertyChanged("FechaCumpleaños");
					this.OnFechaCumpleañosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIdAsignado", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserIdAsignado
		{
			get
			{
				return this._UserIdAsignado;
			}
			set
			{
				if ((this._UserIdAsignado != value))
				{
					this.OnUserIdAsignadoChanging(value);
					this.SendPropertyChanging();
					this._UserIdAsignado = value;
					this.SendPropertyChanged("UserIdAsignado");
					this.OnUserIdAsignadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BrokersMigrar")]
	public partial class BrokersMigrar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Idbroker;
		
		private System.Nullable<bool> _Migracion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdbrokerChanging(System.Nullable<int> value);
    partial void OnIdbrokerChanged();
    partial void OnMigracionChanging(System.Nullable<bool> value);
    partial void OnMigracionChanged();
    #endregion
		
		public BrokersMigrar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idbroker", DbType="Int")]
		public System.Nullable<int> Idbroker
		{
			get
			{
				return this._Idbroker;
			}
			set
			{
				if ((this._Idbroker != value))
				{
					this.OnIdbrokerChanging(value);
					this.SendPropertyChanging();
					this._Idbroker = value;
					this.SendPropertyChanged("Idbroker");
					this.OnIdbrokerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Migracion", DbType="Bit")]
		public System.Nullable<bool> Migracion
		{
			get
			{
				return this._Migracion;
			}
			set
			{
				if ((this._Migracion != value))
				{
					this.OnMigracionChanging(value);
					this.SendPropertyChanging();
					this._Migracion = value;
					this.SendPropertyChanged("Migracion");
					this.OnMigracionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
