<?xml version="1.0" encoding="utf-8"?><Database Name="SAAPA" Class="SAAPADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.23.10.167;Initial Catalog=SAAPA;User ID=migracione" SettingsObjectName="CRM_Migracion.Properties.Settings" SettingsPropertyName="SAAPAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BrokersReferido" Member="BrokersReferido">
    <Type Name="BrokersReferido">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdBroker" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IdTipoReferido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserIdRegistro" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BrokersAltaEjecutivo" Member="BrokersAltaEjecutivo">
    <Type Name="BrokersAltaEjecutivo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdInmobiliaria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoNombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApellidoPaterno" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoMaterno" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserIdRegistro" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdBrokerEmpleado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Curp" Type="System.String" DbType="NVarChar(18)" CanBeNull="true" />
      <Column Name="FechaCumpleaños" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserIdAsignado" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BrokersMigrar" Member="BrokersMigrar">
    <Type Name="BrokersMigrar">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Idbroker" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Migracion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="[.dbo].ActualizarReferido" Method="ActualizarReferido">
    <Parameter Name="IdReferido" Parameter="idReferido" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="[.dbo].InsertarReferido" Method="InsertarReferido">
    <Parameter Name="IdReferido" Parameter="idReferido" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="[.dbo].InsertarAlFinalBrokersReferido" Method="InsertarAlFinalBrokersReferido">
    <Parameter Name="idReferido" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="[.dbo].ActualizarTablasRelacinadasReferidos" Method="ActualizarTablasRelacinadasReferidos">
    <Parameter Name="IdReferidoN" Parameter="idReferidoN" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdReferidoV" Parameter="idReferidoV" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="[.dbo].ActualizarAltaEjecutivo" Method="ActualizarAltaEjecutivo">
    <Parameter Name="IdReferido" Parameter="idReferido" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="[.dbo].InsertarAlFinalAltaEjecutivo" Method="InsertarAlFinalAltaEjecutivo">
    <Parameter Name="idReferido" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="[.dbo].InsertarAltaEjecutivo" Method="InsertarAltaEjecutivo">
    <Parameter Name="IdReferido" Parameter="idReferido" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>